# Generated by Django 3.2.9 on 2022-03-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qav2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='topic_children', to='qav2.Topic'),
        ),
    ]
